#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL THE DATABASE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	"php$php_version" bin/console db:install --db-host="localhost" \
		--db-name="$db_name" --db-password="$db_pwd" --db-user="$db_user" --reconfigure --no-interaction
	"php$php_version" bin/console config:set url_base "https://$domain$path"
	ynh_safe_rm "$install_dir/install/install.php"
popd

chown -R $app:www-data "$install_dir"

#=================================================
# LDAP/SSO CONFIGURATION
#=================================================
ynh_script_progression "Configuring LDAP authentication..."

ynh_mysql_db_shell <<< "INSERT INTO \`glpi_authldaps\` VALUES
(1,'YunoHost','localhost','dc=yunohost,dc=org','',389,'(&#38;(objectClass=posixAccount)(permission=cn=glpi.main,ou=permission,dc=yunohost,dc=org))','uid','entryuuid',0,'memberof','(objectClass = posixGroup)',0,'memberuid','mail','sn','givenname','telephonenumber','homephone','mobile','description',1,0,0,'title','businesscategory','preferredlanguage','ou','(objectClass=organizationalUnit)',NULL,'',1,1,'','employeenumber','','','','l','manager',1000,0,1,'jpegphoto',NULL,NULL,NULL,NULL,1,10);"

# Import the 'admins' and 'all_users' groups from LDAP
ynh_mysql_db_shell <<< "INSERT INTO \`glpi_groups\` VALUES
(1,0,0,'admins',NULL,'memberof','cn=admins,ou=groups,dc=yunohost,dc=org',NULL,NULL,0,'admins',1,'[]','{\"4\":4}',1,1,1,1,1,1,1,1,NULL),
(2,0,0,'all_users',NULL,'memberof','cn=all_users,ou=groups,dc=yunohost,dc=org',NULL,NULL,0,'all_users',1,'[]',NULL,1,1,1,1,1,1,1,1,NULL);"

# Associate users from the 'admins' LDAP group with the 'Super-Admin' GLPI profile
mysqlconn="mysql --user=$db_user --password=$db_pwd --database=$db_name"
lastid=$($mysqlconn -BN -e "SELECT max(id) from \`glpi_rules\`")
lastid=$(("$lastid" + 1 ))
ynh_mysql_db_shell <<< "INSERT INTO \`glpi_rules\` VALUES ($lastid,0,'RuleRight',2,'YunoHost','','AND',1,'',NULL,0,'a287c79c-b2d8e96f-691d1bd7124ca6.38621203',0,NULL);"
ynh_mysql_db_shell <<< "INSERT INTO \`glpi_rulecriterias\` (\`rules_id\`, \`criteria\`, \`condition\`, \`pattern\`) VALUES ($lastid,'_groups_id',0,'1');"
ynh_mysql_db_shell <<< "INSERT INTO \`glpi_ruleactions\` (\`rules_id\`, \`action_type\`, \`field\`, \`value\`) VALUES ($lastid,'assign','profiles_id','4');"

# SSO configuration
pushd "$install_dir"
	"php$php_version" bin/console config:set ssovariables_id "2"
	if ! ynh_permission_has_user --permission=main --user=visitors
	then
		main_domain=$(cat /etc/yunohost/current_host)
		"php$php_version" bin/console config:set ssologout_url "https://$main_domain/yunohost/sso/?action=logout"
	fi
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
