#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL THE DATABASE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console db:install --db-host="localhost" \
		--db-name="$db_name" --db-password="$db_pwd" --db-user="$db_user" --reconfigure --no-interaction
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console config:set url_base "https://$domain$path"
	ynh_safe_rm "$install_dir/install/install.php"
popd

chown -R $app:www-data "$install_dir"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression --message="Configuring Fail2Ban..."

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-access.log" --failregex="^(<HOST>).+(apirest\.php|login\.php).+\"\s40\d\s\d{1,5}"
ynh_replace --match="\[Definition\]" --replace="\[Definition\]\ndatepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?\n              ^[^\\\[]*\\\[({DATE})\n              {^LN-BEG}" --file="/etc/fail2ban/filter.d/glpi__2.conf"
ynh_systemctl --action=restart --service=fail2ban

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
