#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config files marketplace plugins"

#=================================================
# UPDATE THE DATABASE
#=================================================
ynh_script_progression "Updating the database..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console system:check_requirements
	ynh_hide_warnings ynh_exec_as_app php$php_version bin/console db:update --no-interaction --no-telemetry --force
popd

chown -R $app:www-data "$install_dir"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression --message="Configuring Fail2Ban..."

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="$install_dir/files/_log/event.log" --failregex="^\[login\] \d+: Failed login for .* from IP <HOST>$"
ynh_replace --match="\[Definition\]" --replace="\[Definition\]\ndatepattern = ^%%Y-%%m-%%d %%H:%%M:%%S" --file="/etc/fail2ban/filter.d/$app.conf"
ynh_replace --match="filter = $app" --replace="filter = $app\nmaxlines = 2" --file="/etc/fail2ban/jail.d/$app.conf"
ynh_systemctl --action=restart --service=fail2ban

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
